// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3rqZf91rAXte3z9Ih5Lti3WKnjJ-mlmo',
    appId: '1:548483887665:web:147cf1ee357e141e4bdb10',
    messagingSenderId: '548483887665',
    projectId: 'tugas-final-iot',
    authDomain: 'tugas-final-iot.firebaseapp.com',
    databaseURL: 'https://tugas-final-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-final-iot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnz8ZuKy3qzZYMZsWTWHs0Bsp6-FsDBf4',
    appId: '1:548483887665:android:c76dcbfafeed43e34bdb10',
    messagingSenderId: '548483887665',
    projectId: 'tugas-final-iot',
    databaseURL: 'https://tugas-final-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-final-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDklETTRrTxcoNmgLtacqGhRKO5UVTX7w4',
    appId: '1:548483887665:ios:774c8f161e346d8b4bdb10',
    messagingSenderId: '548483887665',
    projectId: 'tugas-final-iot',
    databaseURL: 'https://tugas-final-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-final-iot.appspot.com',
    iosBundleId: 'com.example.finalIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDklETTRrTxcoNmgLtacqGhRKO5UVTX7w4',
    appId: '1:548483887665:ios:9d358ca60ae95d654bdb10',
    messagingSenderId: '548483887665',
    projectId: 'tugas-final-iot',
    databaseURL: 'https://tugas-final-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-final-iot.appspot.com',
    iosBundleId: 'com.example.finalIot.RunnerTests',
  );
}
